### ISSUE TITLE
Replace sleep in diagnostic

### ISSUE THREAD

**Issue by jonpwilson** [bbc/hive-runner-android#17]
In the diagnostic merge, a sleep for 30 seconds while the device reboots - we need to change this so that it will continue as soon as the device becomes available again.

Linked to bbc/device_api-android#63

**Comment by jrmhaig** [comment]
Part of bbc/hive-runner#154

**Comment by Asimk21** [comment]
Waiting for device works for devices connected over usb only. For devices connected over wifi, when device is rebooted it loses adb connection.

**Comment by Asimk21** [comment]
PR to avoid hive fall when detecting device without hivemind https://github.com/bbc/hive-runner-android/pull/79

**Comment by Asimk21** [comment]
closed via bbc/device_api-android#118
