### ISSUE TITLE
Hive-Mind-android reference breaking hive

### ISSUE THREAD

**Issue by Asimk21** [bbc/hive-runner-android#59]
`require 'hive_mind-android'` in `hive-runner-android-1.2.2` is stopping hive. It is required but not added in dependency list.

Output: 
/lib/hive/worker/android.rb:3:in 'require' cannot load suh file -- hive_mind-android (LoadError)

**Comment by jonpwilson** [comment]
Not sure where you're seeing this, as there's nothing on line 3 in the worker: https://github.com/bbc/hive-runner-android/blob/master/lib/hive/worker/android.rb#L3

**Comment by jonpwilson** [comment]
Fixed by updating to hive-runner-android-1.2.3.gem
